"""Delete user_post association, and only allow one user per post

Revision ID: ac4fcc41e102
Revises: 94dc8002f01a
Create Date: 2024-04-06 21:35:27.471737

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac4fcc41e102"
down_revision: Union[str, None] = "94dc8002f01a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_post")
    op.add_column("post", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "post", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post", type_="foreignkey")
    op.drop_column("post", "user_id")
    op.create_table(
        "user_post",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("post_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["post.id"], name="user_post_post_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_post_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("user_id", "post_id", name="user_post_pkey"),
    )
    # ### end Alembic commands ###
