"""Add title to post

Revision ID: e30b1013c045
Revises: 618f535e3823
Create Date: 2024-03-31 00:35:35.192293

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e30b1013c045"
down_revision: Union[str, None] = "618f535e3823"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("title", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "title")
    # ### end Alembic commands ###
